name: Grass Greener

on:
  workflow_dispatch: {}
  schedule:
  - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
    - run: date > date.txt
    - run: git config user.name "Yoshi bot"
    - run: git config user.email "crispy245@gmail.com"
    - run: git add date.txt
    - run: git commit -m 'Greening'
    - run: git push origin main
